### ISSUE TITLE
256 double数组向量，相似度是用余玄夹角计算

### ISSUE THREAD

**Issue by luqinlive** [ChunelFeng/caiss#2]
256 double数组向量，相似度是用余玄夹角计算，可以用caiss做以图搜图吗，另外caiss有交流群吗，谢谢大佬

**Comment by ChunelFeng** [comment]
> 256 double数组向量，相似度是用余玄夹角计算，可以用caiss做以图搜图吗，另外caiss有交流群吗，谢谢大佬

我这边设计的时候，主要考虑的就是cos距离。如果你这边做以图搜图的话，图像的embedding需要你自己做。其他的caiss可以帮你做掉。
一个人自己搞的工程，你可以加我微信，我这边假期的时候，可以答疑的。

**Comment by ChunelFeng** [comment]
> 256 double数组向量，相似度是用余玄夹角计算，可以用caiss做以图搜图吗，另外caiss有交流群吗，谢谢大佬

我的微信，在说明文档里有哈 ： Chunel_Fung
