### ISSUE TITLE
请问这个算法库的性能数据有吗

### ISSUE THREAD

**Issue by goodluckcwl** [ChunelFeng/caiss#3]

**Comment by ChunelFeng** [comment]
Caiss底层主要结构是hnsw，我们在计算层面做了异步计算优化，加入了缓存和并发机制，性能高于原生hnsw。
至于ann算法性能的比较，可以参考前人的一些工作：https://zhuanlan.zhihu.com/p/37381294
做这一套系统，一方面是为了自己实验使用，另一方面是为了其他使用者更方便的接入。
如果有使用需求，欢迎随时联系我们

**Comment by ChunelFeng** [comment]
> 

最近做了一个性能对比，把测试的结果写到说明文档里了。欢迎参考项目下方【推荐阅读】的链接。
