### ISSUE TITLE
docker下运行pythonDemo版本进行句子查询 报错

### ISSUE THREAD

**Issue by Yaningkong** [ChunelFeng/caiss#4]
DIM = 768
#WORD = 'go|home'
WORD = ['go home']
TOP_K = 5
#SEARCH_TYPE = CAISS_SEARCH_WORD
SEARCH_TYPE=CAISS_SEARCH_QUERY
请问相似句查询时 参数WORD或者QUERY应该写怎样的格式

pyCaiss.py：
if search_type == CAISS_SEARCH_QUERY or search_type == CAISS_LOOP_QUERY:
            # 如果传入的是数组信息，需要将数组转成指针传递下去
            #print('len:',len(info))
           # print('self._dim',self._dim)
           # print('info[0]',info[0])
            if self._dim != len(info):
                return CAISS_RET_DIM, ''
            vec = (c_float * self._dim)()
            for i in range(0,int(self._dim)):
                #print('vec',vec[i])
                vec[i] = info[i]
                #print('vec',vec[i])
            ret = self._caiss.CAISS_Search(handle, vec, search_type, top_k, filter_edit_distance, None, None)
pyCaiss.py文件中当我查询格式换成 CAISS_SEARCH_QUERY是 我应该传怎样的info满足vec
这部分不是很懂，恳请解决一下。

**Comment by ChunelFeng** [comment]
请加我微信ChunelFeng，我们具体聊哈

**Comment by ChunelFeng** [comment]
Caiss是一个快速检索引擎，如果你想搜索句子的话，需要自己做embedding，然后按照说明，把句子和对应的向量通过train接口打到*.caiss模型中。
请加我微信 ChunelFeng，欢迎随时交流
