### ISSUE TITLE
底层库是faiss吗?

### ISSUE THREAD

**Issue by sanzado** [ChunelFeng/caiss#6]
索引的逻辑和检索的逻辑是使用的faiss吗? 还是自己开发的?

**Comment by ChunelFeng** [comment]
> 索引的逻辑和检索的逻辑是使用的faiss吗? 还是自己开发的?

用的是开源的hnsw和mrpt，自己拿过来改了一下，做了框架适配，加了eigen计算。

需要的话，可以给您推荐周边大佬开发的ann算法包。
