### ISSUE TITLE
请问这个库是否还在持续的支持？

### ISSUE THREAD

**Issue by yayaQAQ** [ChunelFeng/caiss#7]
我看这个库最近一次更新在一年前，是认为已经完善了？还是不准备持续支持了呢？

**Comment by ChunelFeng** [comment]
您好。  无法认为这个库已经完善，只能基本是自己一段时间的思路的集合吧。
最近一年，很多精力放到了 另外一个repo：CGraph上，参考：https://github.com/ChunelFeng/CGraph

至于ann搜索方面，也在用 CGraph承接，具体算法研究的部分，交由专业的研究团队去做了。
项目参考：https://github.com/whenever5225/GraphANNS

**Comment by ChunelFeng** [comment]
> 我看这个库最近一次更新在一年前，是认为已经完善了？还是不准备持续支持了呢？

感谢您的关注。
如果对项目或者相关领域知识有兴趣的话，欢迎随时指导和交流。
