### ISSUE TITLE
有没有以图搜图的应用案例呀？

### ISSUE THREAD

**Issue by cesaryuan** [ChunelFeng/caiss#8]
首先感谢大佬优秀的项目！

我的场景是这样的，想做一个简单的本地以图搜图引擎，只需要本地运行，没有集群需求，所以觉得大佬这个库十分适合（milvus对于我这个需求来说比较复杂了，而且没有官方的Windows版本支持）。

将图片向量化（embedding）这一步我已经实现了（使用towhee），也就是得到了每个图片的向量，那训练样本的格式如何填写？（其实没太懂这里的训练在训练什么哈哈）

是这样填写吗？
```
{"imagePath1": vector}
{"imagePath2": vector}
```
希望大佬不吝赐教😁

**Comment by ChunelFeng** [comment]
您好，感谢你的关注。

是的，doc/ 文件夹下，有个 `demo_2500words_768dim.txt` 文件，按照里面的格式，将信息写入文件，然后加载即可。

写入的时候，请确保格式和 是否包含引号都一致。
其实就是  下图这种格式。

![image](https://user-images.githubusercontent.com/37905059/205092590-b7c659bf-e07b-461e-b4a9-6ba0a2e83fa9.png)

**Comment by cesaryuan** [comment]
> 是的，doc/ 文件夹下，有个 `demo_2500words_768dim.txt` 文件，按照里面的格式，将信息写入文件，然后加载即可。
> 
> 写入的时候，请确保格式和 是否包含引号都一致。 其实就是 下图这种格式。
> 
> ![image](https://user-images.githubusercontent.com/37905059/205092590-b7c659bf-e07b-461e-b4a9-6ba0a2e83fa9.png)

谢谢大佬回复，就是没太懂在以图搜图这种场景下每一个样本的key应该怎么填写，在相似词搜索场景中，key设置为word本身看起来很容易理解，那在以图搜图场景中，key设置为图片路径是对的吗？

**Comment by ChunelFeng** [comment]
样本的key，就是你的图片（名字或者路径均可啊，只要能区分即可）， value 就是你的 图片 embeding 出来的结果啊。

我也是anns领域的爱好者，如果有兴趣的话，欢迎微信交流。

**Comment by cesaryuan** [comment]
> 样本的key，就是你的图片（名字或者路径均可啊，只要能区分即可）， value 就是你的 图片 embeding 出来的结果啊。
> 
> 我也是anns领域的爱好者，如果有兴趣的话，欢迎微信交流。

大概理解了，谢谢大佬，我明天尝试下，等下加大佬微信嘿嘿
